n = int(input("Digite um número para ver sua tabuada: "))

print("===========")
print("0 x", n,"=",0*n)
print("1 x", n,"=",1*n)
print("2 x", n,"=",2*n)
print("3 x", n,"=",3*n)
print("4 x", n,"=",4*n)
print("5 x", n,"=",5*n)
print("6 x", n,"=",6*n)
print("7 x", n,"=",7*n)
print("8 x", n,"=",8*n)
print("9 x", n,"=",9*n)
print("10 x", n,"=",10*n)
print("===========")